version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tomato_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  web:
    build: .
    command: python webapp.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tomato_db
    depends_on:
      - db

  bot:
    build: .
    command: python bot.py
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tomato_db
    depends_on:
      - db
      - web

volumes:
  dbdata:
